version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: lab_postgres
    environment:
      POSTGRES_DB: laboratorios_db
      POSTGRES_USER: lab_user
      POSTGRES_PASSWORD: lab_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - lab_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: lab_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@lab.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - lab_network

volumes:
  postgres_data:

networks:
  lab_network:
    driver: bridge
